<?php
/**
 * Plan
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  CryptoGate
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CryptoGate\Model;

use \ArrayAccess;
use \CryptoGate\ObjectSerializer;

/**
 * Plan Class Doc Comment
 *
 * @category Class
 * @package  CryptoGate
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Plan implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Plan';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tier' => '\CryptoGate\Model\PlanTier',
        'monthly_price_usd' => 'float',
        'yearly_price_usd' => 'float',
        'monthly_transaction_limit' => 'int',
        'overage_cost_per_tx' => 'float',
        'webhook_support' => 'bool',
        'webhook_limit' => 'int',
        'ip_whitelist' => 'bool',
        'api_rate_limit_per_minute' => 'int',
        'api_rate_limit_per_hour' => 'int',
        'custom_pricing' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tier' => null,
        'monthly_price_usd' => null,
        'yearly_price_usd' => null,
        'monthly_transaction_limit' => null,
        'overage_cost_per_tx' => null,
        'webhook_support' => null,
        'webhook_limit' => null,
        'ip_whitelist' => null,
        'api_rate_limit_per_minute' => null,
        'api_rate_limit_per_hour' => null,
        'custom_pricing' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tier' => false,
        'monthly_price_usd' => true,
        'yearly_price_usd' => true,
        'monthly_transaction_limit' => true,
        'overage_cost_per_tx' => false,
        'webhook_support' => false,
        'webhook_limit' => true,
        'ip_whitelist' => false,
        'api_rate_limit_per_minute' => false,
        'api_rate_limit_per_hour' => false,
        'custom_pricing' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tier' => 'tier',
        'monthly_price_usd' => 'monthly_price_usd',
        'yearly_price_usd' => 'yearly_price_usd',
        'monthly_transaction_limit' => 'monthly_transaction_limit',
        'overage_cost_per_tx' => 'overage_cost_per_tx',
        'webhook_support' => 'webhook_support',
        'webhook_limit' => 'webhook_limit',
        'ip_whitelist' => 'ip_whitelist',
        'api_rate_limit_per_minute' => 'api_rate_limit_per_minute',
        'api_rate_limit_per_hour' => 'api_rate_limit_per_hour',
        'custom_pricing' => 'custom_pricing'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tier' => 'setTier',
        'monthly_price_usd' => 'setMonthlyPriceUsd',
        'yearly_price_usd' => 'setYearlyPriceUsd',
        'monthly_transaction_limit' => 'setMonthlyTransactionLimit',
        'overage_cost_per_tx' => 'setOverageCostPerTx',
        'webhook_support' => 'setWebhookSupport',
        'webhook_limit' => 'setWebhookLimit',
        'ip_whitelist' => 'setIpWhitelist',
        'api_rate_limit_per_minute' => 'setApiRateLimitPerMinute',
        'api_rate_limit_per_hour' => 'setApiRateLimitPerHour',
        'custom_pricing' => 'setCustomPricing'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tier' => 'getTier',
        'monthly_price_usd' => 'getMonthlyPriceUsd',
        'yearly_price_usd' => 'getYearlyPriceUsd',
        'monthly_transaction_limit' => 'getMonthlyTransactionLimit',
        'overage_cost_per_tx' => 'getOverageCostPerTx',
        'webhook_support' => 'getWebhookSupport',
        'webhook_limit' => 'getWebhookLimit',
        'ip_whitelist' => 'getIpWhitelist',
        'api_rate_limit_per_minute' => 'getApiRateLimitPerMinute',
        'api_rate_limit_per_hour' => 'getApiRateLimitPerHour',
        'custom_pricing' => 'getCustomPricing'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tier', $data ?? [], null);
        $this->setIfExists('monthly_price_usd', $data ?? [], null);
        $this->setIfExists('yearly_price_usd', $data ?? [], null);
        $this->setIfExists('monthly_transaction_limit', $data ?? [], null);
        $this->setIfExists('overage_cost_per_tx', $data ?? [], null);
        $this->setIfExists('webhook_support', $data ?? [], null);
        $this->setIfExists('webhook_limit', $data ?? [], null);
        $this->setIfExists('ip_whitelist', $data ?? [], null);
        $this->setIfExists('api_rate_limit_per_minute', $data ?? [], null);
        $this->setIfExists('api_rate_limit_per_hour', $data ?? [], null);
        $this->setIfExists('custom_pricing', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tier
     *
     * @return \CryptoGate\Model\PlanTier|null
     */
    public function getTier()
    {
        return $this->container['tier'];
    }

    /**
     * Sets tier
     *
     * @param \CryptoGate\Model\PlanTier|null $tier tier
     *
     * @return self
     */
    public function setTier($tier)
    {
        if (is_null($tier)) {
            throw new \InvalidArgumentException('non-nullable tier cannot be null');
        }
        $this->container['tier'] = $tier;

        return $this;
    }

    /**
     * Gets monthly_price_usd
     *
     * @return float|null
     */
    public function getMonthlyPriceUsd()
    {
        return $this->container['monthly_price_usd'];
    }

    /**
     * Sets monthly_price_usd
     *
     * @param float|null $monthly_price_usd monthly_price_usd
     *
     * @return self
     */
    public function setMonthlyPriceUsd($monthly_price_usd)
    {
        if (is_null($monthly_price_usd)) {
            array_push($this->openAPINullablesSetToNull, 'monthly_price_usd');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monthly_price_usd', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monthly_price_usd'] = $monthly_price_usd;

        return $this;
    }

    /**
     * Gets yearly_price_usd
     *
     * @return float|null
     */
    public function getYearlyPriceUsd()
    {
        return $this->container['yearly_price_usd'];
    }

    /**
     * Sets yearly_price_usd
     *
     * @param float|null $yearly_price_usd yearly_price_usd
     *
     * @return self
     */
    public function setYearlyPriceUsd($yearly_price_usd)
    {
        if (is_null($yearly_price_usd)) {
            array_push($this->openAPINullablesSetToNull, 'yearly_price_usd');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('yearly_price_usd', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['yearly_price_usd'] = $yearly_price_usd;

        return $this;
    }

    /**
     * Gets monthly_transaction_limit
     *
     * @return int|null
     */
    public function getMonthlyTransactionLimit()
    {
        return $this->container['monthly_transaction_limit'];
    }

    /**
     * Sets monthly_transaction_limit
     *
     * @param int|null $monthly_transaction_limit monthly_transaction_limit
     *
     * @return self
     */
    public function setMonthlyTransactionLimit($monthly_transaction_limit)
    {
        if (is_null($monthly_transaction_limit)) {
            array_push($this->openAPINullablesSetToNull, 'monthly_transaction_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monthly_transaction_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monthly_transaction_limit'] = $monthly_transaction_limit;

        return $this;
    }

    /**
     * Gets overage_cost_per_tx
     *
     * @return float|null
     */
    public function getOverageCostPerTx()
    {
        return $this->container['overage_cost_per_tx'];
    }

    /**
     * Sets overage_cost_per_tx
     *
     * @param float|null $overage_cost_per_tx overage_cost_per_tx
     *
     * @return self
     */
    public function setOverageCostPerTx($overage_cost_per_tx)
    {
        if (is_null($overage_cost_per_tx)) {
            throw new \InvalidArgumentException('non-nullable overage_cost_per_tx cannot be null');
        }
        $this->container['overage_cost_per_tx'] = $overage_cost_per_tx;

        return $this;
    }

    /**
     * Gets webhook_support
     *
     * @return bool|null
     */
    public function getWebhookSupport()
    {
        return $this->container['webhook_support'];
    }

    /**
     * Sets webhook_support
     *
     * @param bool|null $webhook_support webhook_support
     *
     * @return self
     */
    public function setWebhookSupport($webhook_support)
    {
        if (is_null($webhook_support)) {
            throw new \InvalidArgumentException('non-nullable webhook_support cannot be null');
        }
        $this->container['webhook_support'] = $webhook_support;

        return $this;
    }

    /**
     * Gets webhook_limit
     *
     * @return int|null
     */
    public function getWebhookLimit()
    {
        return $this->container['webhook_limit'];
    }

    /**
     * Sets webhook_limit
     *
     * @param int|null $webhook_limit webhook_limit
     *
     * @return self
     */
    public function setWebhookLimit($webhook_limit)
    {
        if (is_null($webhook_limit)) {
            array_push($this->openAPINullablesSetToNull, 'webhook_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('webhook_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['webhook_limit'] = $webhook_limit;

        return $this;
    }

    /**
     * Gets ip_whitelist
     *
     * @return bool|null
     */
    public function getIpWhitelist()
    {
        return $this->container['ip_whitelist'];
    }

    /**
     * Sets ip_whitelist
     *
     * @param bool|null $ip_whitelist ip_whitelist
     *
     * @return self
     */
    public function setIpWhitelist($ip_whitelist)
    {
        if (is_null($ip_whitelist)) {
            throw new \InvalidArgumentException('non-nullable ip_whitelist cannot be null');
        }
        $this->container['ip_whitelist'] = $ip_whitelist;

        return $this;
    }

    /**
     * Gets api_rate_limit_per_minute
     *
     * @return int|null
     */
    public function getApiRateLimitPerMinute()
    {
        return $this->container['api_rate_limit_per_minute'];
    }

    /**
     * Sets api_rate_limit_per_minute
     *
     * @param int|null $api_rate_limit_per_minute api_rate_limit_per_minute
     *
     * @return self
     */
    public function setApiRateLimitPerMinute($api_rate_limit_per_minute)
    {
        if (is_null($api_rate_limit_per_minute)) {
            throw new \InvalidArgumentException('non-nullable api_rate_limit_per_minute cannot be null');
        }
        $this->container['api_rate_limit_per_minute'] = $api_rate_limit_per_minute;

        return $this;
    }

    /**
     * Gets api_rate_limit_per_hour
     *
     * @return int|null
     */
    public function getApiRateLimitPerHour()
    {
        return $this->container['api_rate_limit_per_hour'];
    }

    /**
     * Sets api_rate_limit_per_hour
     *
     * @param int|null $api_rate_limit_per_hour api_rate_limit_per_hour
     *
     * @return self
     */
    public function setApiRateLimitPerHour($api_rate_limit_per_hour)
    {
        if (is_null($api_rate_limit_per_hour)) {
            throw new \InvalidArgumentException('non-nullable api_rate_limit_per_hour cannot be null');
        }
        $this->container['api_rate_limit_per_hour'] = $api_rate_limit_per_hour;

        return $this;
    }

    /**
     * Gets custom_pricing
     *
     * @return bool|null
     */
    public function getCustomPricing()
    {
        return $this->container['custom_pricing'];
    }

    /**
     * Sets custom_pricing
     *
     * @param bool|null $custom_pricing custom_pricing
     *
     * @return self
     */
    public function setCustomPricing($custom_pricing)
    {
        if (is_null($custom_pricing)) {
            throw new \InvalidArgumentException('non-nullable custom_pricing cannot be null');
        }
        $this->container['custom_pricing'] = $custom_pricing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


