<?php
/**
 * Transaction
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GriffNode
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate).
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GriffNode\Model;

use \ArrayAccess;
use \GriffNode\ObjectSerializer;

/**
 * Transaction Class Doc Comment
 *
 * @category Class
 * @description The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed.
 * @package  GriffNode
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Transaction implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Transaction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'transaction_id' => 'string',
        'status' => '\GriffNode\Model\TransactionStatus',
        'type' => 'string',
        'crypto' => '\GriffNode\Model\CryptoSymbol',
        'deposit_address' => 'string',
        'amount_crypto' => 'float',
        'amount_fiat' => 'float',
        'amount_usd' => 'float',
        'amount_paid' => 'float',
        'amount_remaining' => 'float',
        'currency_fiat' => '\GriffNode\Model\FiatCurrency',
        'fiat_to_usd_rate' => 'float',
        'exchange_rate' => 'float',
        'confirmations_required' => 'int',
        'payment_url' => 'string',
        'order_id' => 'string',
        'customer_email' => 'string',
        'items' => '\GriffNode\Model\LineItem[]',
        'payments' => '\GriffNode\Model\PaymentSplit[]',
        'metadata' => 'array<string,string>',
        'success_url' => 'string',
        'cancel_url' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'expires_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'transaction_id' => null,
        'status' => null,
        'type' => null,
        'crypto' => null,
        'deposit_address' => null,
        'amount_crypto' => null,
        'amount_fiat' => null,
        'amount_usd' => null,
        'amount_paid' => null,
        'amount_remaining' => null,
        'currency_fiat' => null,
        'fiat_to_usd_rate' => null,
        'exchange_rate' => null,
        'confirmations_required' => null,
        'payment_url' => 'uri',
        'order_id' => null,
        'customer_email' => null,
        'items' => null,
        'payments' => null,
        'metadata' => null,
        'success_url' => null,
        'cancel_url' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'expires_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'transaction_id' => false,
        'status' => false,
        'type' => false,
        'crypto' => false,
        'deposit_address' => false,
        'amount_crypto' => false,
        'amount_fiat' => false,
        'amount_usd' => false,
        'amount_paid' => false,
        'amount_remaining' => false,
        'currency_fiat' => false,
        'fiat_to_usd_rate' => false,
        'exchange_rate' => false,
        'confirmations_required' => false,
        'payment_url' => false,
        'order_id' => true,
        'customer_email' => true,
        'items' => true,
        'payments' => false,
        'metadata' => false,
        'success_url' => true,
        'cancel_url' => true,
        'created_at' => false,
        'updated_at' => false,
        'expires_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_id' => 'transaction_id',
        'status' => 'status',
        'type' => 'type',
        'crypto' => 'crypto',
        'deposit_address' => 'deposit_address',
        'amount_crypto' => 'amount_crypto',
        'amount_fiat' => 'amount_fiat',
        'amount_usd' => 'amount_usd',
        'amount_paid' => 'amount_paid',
        'amount_remaining' => 'amount_remaining',
        'currency_fiat' => 'currency_fiat',
        'fiat_to_usd_rate' => 'fiat_to_usd_rate',
        'exchange_rate' => 'exchange_rate',
        'confirmations_required' => 'confirmations_required',
        'payment_url' => 'payment_url',
        'order_id' => 'order_id',
        'customer_email' => 'customer_email',
        'items' => 'items',
        'payments' => 'payments',
        'metadata' => 'metadata',
        'success_url' => 'success_url',
        'cancel_url' => 'cancel_url',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'expires_at' => 'expires_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transaction_id' => 'setTransactionId',
        'status' => 'setStatus',
        'type' => 'setType',
        'crypto' => 'setCrypto',
        'deposit_address' => 'setDepositAddress',
        'amount_crypto' => 'setAmountCrypto',
        'amount_fiat' => 'setAmountFiat',
        'amount_usd' => 'setAmountUsd',
        'amount_paid' => 'setAmountPaid',
        'amount_remaining' => 'setAmountRemaining',
        'currency_fiat' => 'setCurrencyFiat',
        'fiat_to_usd_rate' => 'setFiatToUsdRate',
        'exchange_rate' => 'setExchangeRate',
        'confirmations_required' => 'setConfirmationsRequired',
        'payment_url' => 'setPaymentUrl',
        'order_id' => 'setOrderId',
        'customer_email' => 'setCustomerEmail',
        'items' => 'setItems',
        'payments' => 'setPayments',
        'metadata' => 'setMetadata',
        'success_url' => 'setSuccessUrl',
        'cancel_url' => 'setCancelUrl',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'expires_at' => 'setExpiresAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transaction_id' => 'getTransactionId',
        'status' => 'getStatus',
        'type' => 'getType',
        'crypto' => 'getCrypto',
        'deposit_address' => 'getDepositAddress',
        'amount_crypto' => 'getAmountCrypto',
        'amount_fiat' => 'getAmountFiat',
        'amount_usd' => 'getAmountUsd',
        'amount_paid' => 'getAmountPaid',
        'amount_remaining' => 'getAmountRemaining',
        'currency_fiat' => 'getCurrencyFiat',
        'fiat_to_usd_rate' => 'getFiatToUsdRate',
        'exchange_rate' => 'getExchangeRate',
        'confirmations_required' => 'getConfirmationsRequired',
        'payment_url' => 'getPaymentUrl',
        'order_id' => 'getOrderId',
        'customer_email' => 'getCustomerEmail',
        'items' => 'getItems',
        'payments' => 'getPayments',
        'metadata' => 'getMetadata',
        'success_url' => 'getSuccessUrl',
        'cancel_url' => 'getCancelUrl',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'expires_at' => 'getExpiresAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_BASIC = 'basic';
    public const TYPE_DETAILED = 'detailed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_BASIC,
            self::TYPE_DETAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('transaction_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('crypto', $data ?? [], null);
        $this->setIfExists('deposit_address', $data ?? [], null);
        $this->setIfExists('amount_crypto', $data ?? [], null);
        $this->setIfExists('amount_fiat', $data ?? [], null);
        $this->setIfExists('amount_usd', $data ?? [], null);
        $this->setIfExists('amount_paid', $data ?? [], null);
        $this->setIfExists('amount_remaining', $data ?? [], null);
        $this->setIfExists('currency_fiat', $data ?? [], null);
        $this->setIfExists('fiat_to_usd_rate', $data ?? [], null);
        $this->setIfExists('exchange_rate', $data ?? [], null);
        $this->setIfExists('confirmations_required', $data ?? [], null);
        $this->setIfExists('payment_url', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('customer_email', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
        $this->setIfExists('payments', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('success_url', $data ?? [], null);
        $this->setIfExists('cancel_url', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['transaction_id'] === null) {
            $invalidProperties[] = "'transaction_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['crypto'] === null) {
            $invalidProperties[] = "'crypto' can't be null";
        }
        if ($this->container['amount_fiat'] === null) {
            $invalidProperties[] = "'amount_fiat' can't be null";
        }
        if ($this->container['amount_usd'] === null) {
            $invalidProperties[] = "'amount_usd' can't be null";
        }
        if ($this->container['currency_fiat'] === null) {
            $invalidProperties[] = "'currency_fiat' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['expires_at'] === null) {
            $invalidProperties[] = "'expires_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transaction_id
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string $transaction_id transaction_id
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        if (is_null($transaction_id)) {
            throw new \InvalidArgumentException('non-nullable transaction_id cannot be null');
        }
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \GriffNode\Model\TransactionStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \GriffNode\Model\TransactionStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets crypto
     *
     * @return \GriffNode\Model\CryptoSymbol
     */
    public function getCrypto()
    {
        return $this->container['crypto'];
    }

    /**
     * Sets crypto
     *
     * @param \GriffNode\Model\CryptoSymbol $crypto crypto
     *
     * @return self
     */
    public function setCrypto($crypto)
    {
        if (is_null($crypto)) {
            throw new \InvalidArgumentException('non-nullable crypto cannot be null');
        }
        $this->container['crypto'] = $crypto;

        return $this;
    }

    /**
     * Gets deposit_address
     *
     * @return string|null
     */
    public function getDepositAddress()
    {
        return $this->container['deposit_address'];
    }

    /**
     * Sets deposit_address
     *
     * @param string|null $deposit_address deposit_address
     *
     * @return self
     */
    public function setDepositAddress($deposit_address)
    {
        if (is_null($deposit_address)) {
            throw new \InvalidArgumentException('non-nullable deposit_address cannot be null');
        }
        $this->container['deposit_address'] = $deposit_address;

        return $this;
    }

    /**
     * Gets amount_crypto
     *
     * @return float|null
     */
    public function getAmountCrypto()
    {
        return $this->container['amount_crypto'];
    }

    /**
     * Sets amount_crypto
     *
     * @param float|null $amount_crypto amount_crypto
     *
     * @return self
     */
    public function setAmountCrypto($amount_crypto)
    {
        if (is_null($amount_crypto)) {
            throw new \InvalidArgumentException('non-nullable amount_crypto cannot be null');
        }
        $this->container['amount_crypto'] = $amount_crypto;

        return $this;
    }

    /**
     * Gets amount_fiat
     *
     * @return float
     */
    public function getAmountFiat()
    {
        return $this->container['amount_fiat'];
    }

    /**
     * Sets amount_fiat
     *
     * @param float $amount_fiat amount_fiat
     *
     * @return self
     */
    public function setAmountFiat($amount_fiat)
    {
        if (is_null($amount_fiat)) {
            throw new \InvalidArgumentException('non-nullable amount_fiat cannot be null');
        }
        $this->container['amount_fiat'] = $amount_fiat;

        return $this;
    }

    /**
     * Gets amount_usd
     *
     * @return float
     */
    public function getAmountUsd()
    {
        return $this->container['amount_usd'];
    }

    /**
     * Sets amount_usd
     *
     * @param float $amount_usd amount_usd
     *
     * @return self
     */
    public function setAmountUsd($amount_usd)
    {
        if (is_null($amount_usd)) {
            throw new \InvalidArgumentException('non-nullable amount_usd cannot be null');
        }
        $this->container['amount_usd'] = $amount_usd;

        return $this;
    }

    /**
     * Gets amount_paid
     *
     * @return float|null
     */
    public function getAmountPaid()
    {
        return $this->container['amount_paid'];
    }

    /**
     * Sets amount_paid
     *
     * @param float|null $amount_paid amount_paid
     *
     * @return self
     */
    public function setAmountPaid($amount_paid)
    {
        if (is_null($amount_paid)) {
            throw new \InvalidArgumentException('non-nullable amount_paid cannot be null');
        }
        $this->container['amount_paid'] = $amount_paid;

        return $this;
    }

    /**
     * Gets amount_remaining
     *
     * @return float|null
     */
    public function getAmountRemaining()
    {
        return $this->container['amount_remaining'];
    }

    /**
     * Sets amount_remaining
     *
     * @param float|null $amount_remaining amount_remaining
     *
     * @return self
     */
    public function setAmountRemaining($amount_remaining)
    {
        if (is_null($amount_remaining)) {
            throw new \InvalidArgumentException('non-nullable amount_remaining cannot be null');
        }
        $this->container['amount_remaining'] = $amount_remaining;

        return $this;
    }

    /**
     * Gets currency_fiat
     *
     * @return \GriffNode\Model\FiatCurrency
     */
    public function getCurrencyFiat()
    {
        return $this->container['currency_fiat'];
    }

    /**
     * Sets currency_fiat
     *
     * @param \GriffNode\Model\FiatCurrency $currency_fiat currency_fiat
     *
     * @return self
     */
    public function setCurrencyFiat($currency_fiat)
    {
        if (is_null($currency_fiat)) {
            throw new \InvalidArgumentException('non-nullable currency_fiat cannot be null');
        }
        $this->container['currency_fiat'] = $currency_fiat;

        return $this;
    }

    /**
     * Gets fiat_to_usd_rate
     *
     * @return float|null
     */
    public function getFiatToUsdRate()
    {
        return $this->container['fiat_to_usd_rate'];
    }

    /**
     * Sets fiat_to_usd_rate
     *
     * @param float|null $fiat_to_usd_rate fiat_to_usd_rate
     *
     * @return self
     */
    public function setFiatToUsdRate($fiat_to_usd_rate)
    {
        if (is_null($fiat_to_usd_rate)) {
            throw new \InvalidArgumentException('non-nullable fiat_to_usd_rate cannot be null');
        }
        $this->container['fiat_to_usd_rate'] = $fiat_to_usd_rate;

        return $this;
    }

    /**
     * Gets exchange_rate
     *
     * @return float|null
     */
    public function getExchangeRate()
    {
        return $this->container['exchange_rate'];
    }

    /**
     * Sets exchange_rate
     *
     * @param float|null $exchange_rate USD per unit of crypto, locked at creation.
     *
     * @return self
     */
    public function setExchangeRate($exchange_rate)
    {
        if (is_null($exchange_rate)) {
            throw new \InvalidArgumentException('non-nullable exchange_rate cannot be null');
        }
        $this->container['exchange_rate'] = $exchange_rate;

        return $this;
    }

    /**
     * Gets confirmations_required
     *
     * @return int|null
     */
    public function getConfirmationsRequired()
    {
        return $this->container['confirmations_required'];
    }

    /**
     * Sets confirmations_required
     *
     * @param int|null $confirmations_required confirmations_required
     *
     * @return self
     */
    public function setConfirmationsRequired($confirmations_required)
    {
        if (is_null($confirmations_required)) {
            throw new \InvalidArgumentException('non-nullable confirmations_required cannot be null');
        }
        $this->container['confirmations_required'] = $confirmations_required;

        return $this;
    }

    /**
     * Gets payment_url
     *
     * @return string|null
     */
    public function getPaymentUrl()
    {
        return $this->container['payment_url'];
    }

    /**
     * Sets payment_url
     *
     * @param string|null $payment_url payment_url
     *
     * @return self
     */
    public function setPaymentUrl($payment_url)
    {
        if (is_null($payment_url)) {
            throw new \InvalidArgumentException('non-nullable payment_url cannot be null');
        }
        $this->container['payment_url'] = $payment_url;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return string|null
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string|null $order_id order_id
     *
     * @return self
     */
    public function setOrderId($order_id)
    {
        if (is_null($order_id)) {
            array_push($this->openAPINullablesSetToNull, 'order_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets customer_email
     *
     * @return string|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customer_email'];
    }

    /**
     * Sets customer_email
     *
     * @param string|null $customer_email customer_email
     *
     * @return self
     */
    public function setCustomerEmail($customer_email)
    {
        if (is_null($customer_email)) {
            array_push($this->openAPINullablesSetToNull, 'customer_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_email'] = $customer_email;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \GriffNode\Model\LineItem[]|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \GriffNode\Model\LineItem[]|null $items items
     *
     * @return self
     */
    public function setItems($items)
    {
        if (is_null($items)) {
            array_push($this->openAPINullablesSetToNull, 'items');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('items', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets payments
     *
     * @return \GriffNode\Model\PaymentSplit[]|null
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     *
     * @param \GriffNode\Model\PaymentSplit[]|null $payments On-chain payments detected toward this transaction.
     *
     * @return self
     */
    public function setPayments($payments)
    {
        if (is_null($payments)) {
            throw new \InvalidArgumentException('non-nullable payments cannot be null');
        }
        $this->container['payments'] = $payments;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets success_url
     *
     * @return string|null
     */
    public function getSuccessUrl()
    {
        return $this->container['success_url'];
    }

    /**
     * Sets success_url
     *
     * @param string|null $success_url success_url
     *
     * @return self
     */
    public function setSuccessUrl($success_url)
    {
        if (is_null($success_url)) {
            array_push($this->openAPINullablesSetToNull, 'success_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('success_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['success_url'] = $success_url;

        return $this;
    }

    /**
     * Gets cancel_url
     *
     * @return string|null
     */
    public function getCancelUrl()
    {
        return $this->container['cancel_url'];
    }

    /**
     * Sets cancel_url
     *
     * @param string|null $cancel_url cancel_url
     *
     * @return self
     */
    public function setCancelUrl($cancel_url)
    {
        if (is_null($cancel_url)) {
            array_push($this->openAPINullablesSetToNull, 'cancel_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancel_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancel_url'] = $cancel_url;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime $expires_at expires_at
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            throw new \InvalidArgumentException('non-nullable expires_at cannot be null');
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


